### PR TITLE
Fix compliance badge asset resolution issues

### PR DESCRIPTION
**Pull request by inerds**
- image assets now uses 2x resolution assets
- SVG asset uses outlined and flattened version

### CODE REVIEW

**Comment by mbasaglia** [comment]
Should we change the names and such if the resolution is changed?

**Comment by inerds** [comment]
@mbasaglia I don’t think we need to change the name. 
Why are we using 2x resolutions to accommodate high DPI displays like Retina displays.  

Adding dimensions or sizes to the names is an improvement worth considering.

**Comment by Aidosmf** [comment]
@inerds I agree with Matt, we should change the naming. I am ok to use 2x resolutions, other than that LGTM, thanks

**Comment by inerds** [comment]
@Aidosmf i have updated the file names to use actual height as per the suggestion. 7d6f4ae4f238ae87e14c207af90c77e84df10e03

**Review by Aidosmf — APPROVED** [review]
thx, let's wait for @mbasaglia approval

**Review by mbasaglia — APPROVED** [review]

**Pull request merged**
